INSERT INTO VACINA VALUES('CoronaVac',2,0);
INSERT INTO VACINA VALUES('AstraZeneca',2,1);
INSERT INTO VACINA VALUES('SputnikV',2,1);
INSERT INTO VACINA VALUES('Pfizer',2,1);
INSERT INTO VACINA VALUES('Johnson&Johnson',1,1);
INSERT INTO VACINA VALUES('Butanvac',1,0);
INSERT INTO VACINA VALUES('Versamune',1,0);	
